// Generated by the Freon Language Generator.
import {FreCombinedActions, FreProjection, FreScoper, FreStdlib, FreTyper} from "@freon4dsl/core";
import {CustomPropertiesActions, CustomPropertiesProjection} from "../editor";
import {CustomPropertiesValidator} from "../validator";
import {PropertiesCheckerInterface} from "../validator/gen";
import {CustomPropertiesScoper} from "../scoper";
import {CustomPropertiesTyperPart} from "../typer";
import {CustomPropertiesStdlib} from "../stdlib";

/**
 * Class FreonConfiguration is the place where you can add all your customisations.
 * These will be used through the 'freonConfiguration' constant by any generated
 * part of your language environment.
 */
class FreonConfiguration {
    // add your custom editor projections here
    customProjection: FreProjection[] = [new CustomPropertiesProjection()];
    // add your custom editor actions here
    customActions: FreCombinedActions[] = [new CustomPropertiesActions()];
    // add your custom validations here
    customValidations: PropertiesCheckerInterface[] = [new CustomPropertiesValidator()];
    // add your custom scopers here
    customScopers: FreScoper[] = [new CustomPropertiesScoper()];
    // add your custom type-providers here
    customTypers: FreTyper[] = [new CustomPropertiesTyperPart()];
    // add extra predefined instances here
    customStdLibs: FreStdlib[] = [new CustomPropertiesStdlib()];
}

export const freonConfiguration = new FreonConfiguration();
