// Generated by the Freon Language Generator.
import { FreProjection, FreCombinedActions, FreTyper, FreStdlib, FreScoper } from "@freon4dsl/core";
import { CustomMyLanguageActions, CustomMyLanguageProjection } from "../editor";
import { CustomMyLanguageScoper } from "../scoper";
import { CustomMyLanguageTyperPart } from "../typer";
import { CustomMyLanguageValidator } from "../validator";
import { CustomMyLanguageStdlib } from "../stdlib";
import { MyLanguageCheckerInterface } from "../validator/gen";

/**
 * Class FreonConfiguration is the place where you can add all your customisations.
 * These will be used through the 'freonConfiguration' constant by any generated
 * part of your language environment.
 */
class FreonConfiguration {
    // add your custom editor projections here
    customProjection: FreProjection[] = [new CustomMyLanguageProjection()];
    // add your custom editor actions here
    customActions: FreCombinedActions[] = [new CustomMyLanguageActions()];
    // add your custom validations here
    customValidations: MyLanguageCheckerInterface[] = [new CustomMyLanguageValidator()];
    // add your custom scopers here
    customScopers: FreScoper[] = [new CustomMyLanguageScoper()];
    // add your custom type-providers here
    customTypers: FreTyper[] = [new CustomMyLanguageTyperPart()];
    // add extra predefined instances here
    customStdLibs: FreStdlib[] = [new CustomMyLanguageStdlib()];
}

export const freonConfiguration = new FreonConfiguration();
