// Generated by the Freon Language Generator.
import { FreError, FreErrorSeverity } from "@freon4dsl/core";
import { SimpleformsDefaultWorker } from "../utils/gen/SimpleformsDefaultWorker";
import { SimpleformsCheckerInterface } from "./gen/SimpleformsValidator";

export class CustomSimpleformsValidator extends SimpleformsDefaultWorker implements SimpleformsCheckerInterface {
    errorList: FreError[] = [];
}
