// Generated by the Freon Language Generator.
import { FreError, FreErrorSeverity } from "@freon4dsl/core";
import { MyLanguageDefaultWorker } from "../utils/gen/MyLanguageDefaultWorker";
import { MyLanguageCheckerInterface } from "./gen/MyLanguageValidator";

export class CustomMyLanguageValidator extends MyLanguageDefaultWorker implements MyLanguageCheckerInterface {
    errorList: FreError[] = [];
}
