// Generated by the Freon Language Generator.
import { FreError, FreErrorSeverity } from "@freon4dsl/core";
import { PropertiesDefaultWorker } from "../utils/gen/PropertiesDefaultWorker";
import { PropertiesCheckerInterface } from "./gen/PropertiesValidator";

export class CustomPropertiesValidator extends PropertiesDefaultWorker implements PropertiesCheckerInterface {
    errorList: FreError[] = [];
}
