name: Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11' ]
    name: Java ${{ matrix.Java }} BuildAndTest

    steps:
      - uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Generate AST classes
        run: ./gradlew :properties-parser:generateASTClasses
      - name: Test
        run: ./gradlew :properties-parser:check